# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: 5136
#subtitle:
subtitle: Siegfried SEKKAI - DevOps Crafter (SKALE-5)

# Title attribute of HTML Page, uses 'name' from above if empty
title:

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: 5136fried SEKKAI, DevOps Enabler, Skaler. Retrouvez ici mes réseaux et publications.
    keywords: 5136, DevOps, Ops, Skale-5, Siegfried SEKKAI
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://www.5136.me

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/5136fried'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
#    account: 'UA-120960520-1'
#    cookieconsent: true
#    anonymizeip: true


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "https://avatars0.githubusercontent.com/u/74210317"
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - xing:
      name: Xing
      show: false
      href: https://www.xing.com/profile/YOUR_XING_USERNAME/
      icon: fab fa-xing
  - linkedin:
      name: LinkedIn
      show: true
      href: https://linkedin.com/in/siegfried-sekkai/
      icon: fab fa-linkedin
  - googleplus:
      name: Google+
      show: false
      href: https://plus.google.com/+YOUR_GOOGLEPLUS_USERNAME
      icon: fab fa-google-plus
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/YOUR_TWITTER_USERNAME
      icon: fab fa-twitter
  - weibo:
      name: 微博
      show: true
      href: https://weibo.com/YOUR_WEIBO_USERNAME
      icon: fab fa-weibo
  - vine:
      name: Vine
      show: false
      href: https://vine.co/YOUR_VINE_USERNAME
      icon: fab fa-vine
  - facebook:
      name: Facebook
      show: true
      href: https://facebook.com/SiegSteppenWolf
      icon: fab fa-facebook
  - vkontakte:
      name: ВКонтакте
      show: true
      href: https://vk.com/YOUR_VK_USERNAME
      icon: fab fa-vk
  - instagram:
      name: Instagram
      show: true
      href: https://instagram.com/siegserigala
      icon: fab fa-instagram
  - flickr:
      name: Flickr
      show: false
      href: https://flickr.com/photos/YOUR_FLICKR_USERNAME
      icon: fab fa-flickr
  - steam:
      name: Steam
      show: true
      href: http://steamcommunity.com/id/siegsteppenwolf
      icon: fab fa-steam
  - soundcloud:
      name: Soundcloud
      show: false
      href: https://soundcloud.com/YOUR_SOUNDCLOUD_USERNAME
      icon: fab fa-soundcloud
  - lastfm:
      name: Last.fm
      show: false
      href: http://www.last.fm/user/YOUR_LASTFM_USERNAME
      icon: fab fa-lastfm
  - github:
      name: GitHub
      show: true
      href: https://github.com/5136fried
      icon: fab fa-github
  - codepen:
      name: CodePen
      show: false
      href: https://codepen.io/YOUR_CODEPEN_USERNAME
      icon: fab fa-codepen
  - stackoverflow:
      name: Stack Overflow
      show: false
      href: https://stackoverflow.com/users/YOUR_SO_USERNAME/
      icon: fab fa-stack-overflow
  - reddit:
      name: Reddit
      show: false
      href: https://reddit.com/user/YOUR_REDDIT_USERNAME
      icon: fab fa-reddit
  - medium:
      name: Medium
      show: true
      href: https://medium.com/@siegfried.sekkai
      icon: fab fa-medium
  - tumblr:
      name: Tumblr
      show: false
      href: https://YOUR_TUMBLR_USERNAME.tumblr.com/
      icon: fab fa-tumblr
  - blog:
      name: Blog
      show: true
      href: http://5136.me/blog
      icon: fas fa-book-open
  - email:
      name: Email
      show: true
      href: mailto:siegfried.sekkai@gmail.com
      icon: fas fa-envelope
  - publickey:
      name: PGP Key
      show: false
      href: https://pastebin.com/raw/YOUR_PUBLIC_KEY
      icon: fas fa-key
  - Goodread:
      name: Goodread
      show: true
      href: https://www.goodreads.com/user/show/50496480-siegfried-steppenwolf
      icon: fab fa-goodread


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
    Any (multiline) text containing simple HTML,
    such as links or ... lorem ipsum.

#EOF
